name-template: v$NEXT_MINOR_VERSION 🌈
tag-template: configuration-as-code-$NEXT_MINOR_VERSION
categories:
  - title: 🚀 Features
    label: feature
  - title: 🐛 Bug Fixes
    label: fix
  - title: 👻 Maintenance
    label: chore
  - title: 📝 Documentation updates
    label: documentation
  - title: 🚦 Tests
    label: test

template: |
  ## Changes

  $CHANGES
