image:
  - Visual Studio 2017

environment:
  global:
    JAVA_LEVEL: 8
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      MVN_FLAG: -Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true
    - JAVA_HOME: C:\Program Files\Java\jdk11
      MVN_FLAG: -Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true


test: off

install:
  - ps: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V $env:MVN_FLAG

build_script:
  - ps: >-
    mvn clean install -B \
      -Djava.level=$env:JAVA_LEVEL \
      $env:MVN_FLAG
