image:
  - Visual Studio 2017

environment:
  global:
    JAVA_LEVEL: 8
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
      MVN_FLAG: -Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true
    - JAVA_HOME: C:\Program Files\Java\jdk11
      MVN_FLAG: -Djenkins.version=2.164.1 -Daccess-modifier-checker.failOnError=true

test: off

install:
  - cmd: mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B -V %MVN_FLAG%

build_script:
  - cmd: echo "APPVEYOR %APPVEYOR%"
  - cmd: mvn clean install -B -Djava.level=%JAVA_LEVEL% %MVN_FLAG%

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false

