FROM jenkins/jenkins:lts-alpine-casc

ENV CASC_JENKINS_CONFIG=/usr/share/jenkins/ref/jenkins.yaml

# Derived image can just provide jenkins.yaml and plugins.txt files in context, will be automatically included

ONBUILD COPY --chown=jenkins plugins.txt /usr/share/jenkins/ref/plugins.txt
ONBUILD RUN install-plugins.sh < /usr/share/jenkins/ref/plugins.txt
ONBUILD COPY --chown=jenkins jenkins.yaml /usr/share/jenkins/ref/jenkins.yaml
