name: '📝 Documentation'
labels: 'documentation'
description: 'Let us know if any documentation is missing or could be improved'

body:
  - type: textarea
    attributes:
      label: Describe your use-case which is not covered by existing documentation.
      description: If it is easier to submit a documentation patch instead of writing an issue, just do it!
    validations:
      required: true

  - type: textarea
    attributes:
      label: Reference any relevant documentation, other materials or issues/pull requests that can be used for inspiration.
