github:
  user: "GitHub Actions"
  email: "41898282+github-actions[bot]@users.noreply.github.com"
  username: "github-actions"
  token: "UPDATECLI_GITHUB_TOKEN"
  owner: "jenkinsci"
  repository: "configuration-as-code-plugin"
  branch: "master"
