jenkins:
  systemMessage: "Jenkins configured automatically by Jenkins Configuration as Code plugin\n\n"

tool:
  terraforminstallation:
    installations:
      - name: terraform
        home: ""
        properties:
          - installSource:
              installers:
                - terraformInstaller:
                    id: '0.11.9-linux-amd64'

jobs:
  - script: >
      job("terraform-job") {
        description()
        keepDependencies(false)
        disabled(false)
        concurrentBuild(false)
        wrappers {
           terraformBuildWrapper {
              variables("") 
              terraformInstallation("terraform")
              doGetUpdate(true)
              doNotApply(false)
              doDestroy(false)
              config {
                 value("inline")
                 inlineConfig("")
                 fileConfig("")
              }
           }
        }
      }
