name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build on Jenkins ${{ matrix.jenkins-version }}, JDK ${{ matrix.java }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [1.8, 11]
        jenkins-version: [2.60.3, 2.176.3]
        os: [ubuntu-latest, windows-latest]
        include:
        - jenkins-version: '2.176.3'
          flags: '--define jenkins.version=2.176.3'
        exclude:
        - java: '11'
          jenkins-version: '2.60.3'

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: |
        mvn install -B -V --no-transfer-progress ${{ matrix.flags }}
